name: Deploy
env:
    EB_PACKAGE_S3_BUCKET_NAME: 'elasticbeanstalk-us-east-2-018113552303'
    EB_APPLICATION_NAME: 'eslit-prettier'
    EB_ENVIRONMENT_NAME: 'node-express-env'
    EB_PLATFORM_NAME: 'node.js'
    DEPLOY_PACKAGE_NAME: 'node_app_${{ github.sha }}.zip'
    AWS_REGION_NAME: 'us-east-2'
    EB_: 'us-east-2'

'on':
    push:
        branches:
            - lab1

jobs:
    my_ci_part:
        runs-on: ubuntu-latest
        steps:
            - name: Git clone our repo
              uses: actions/checkout@v2

            - name: Configure my AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION_NAME }}

            - name: Install EB
              run: pip install awsebcli --upgrade --user

            - name: EB init
              run: eb init ${{ env.EB_APPLICATION_NAME }} --region ${{ env.AWS_REGION_NAME }} --platform ${{ env.EB_PLATFORM_NAME }}

            - name: Create Zip deploy package
              run: eb deploy
